import './globals.css';
import NavBar from '../components/HomePage/NavBar';
import Footer from '../components/HomePage/Footer';
import CookieSettingsMessage from '../components/HomePage/CookieSettingsMessage';
import ScrollToMiddle from '../components/common/ScrollToMiddle';
export const metadata = {
  title: "NHS UK",
  description: "Generated by chisquare",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <CookieSettingsMessage/>
        <NavBar/>
        <ScrollToMiddle/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
